iMooc/apps/course/urls.py
from django.conf.urls import url, include
from .views import *

urlpatterns = [
    # 课程列表页
    url(r'^list/$', CourseListView.as_view(), name='course_list'),
    # 课程详情页
    url(r'^detail/(?P<course_id>\d+)/', CourseDetailView.as_view(), name='course_detail'),
    # 课程章节详细页
    url(r'^info/(?P<course_id>\d+)/', CourseInfoView.as_view(), name='course_info'),
    # 课程评论
    url(r'^comment/(?P<course_id>\d+)/', CommentView.as_view(), name='course_comment'),
    # 添加课程评论
    url(r'^add_comment/$', AddCommentView.as_view(), name='add_comment'),

    url(r'^video_play/(?P<video_id>\d+)/', VideoPlayView.as_view(), name='video_play'),
]

iMooc/apps/operation/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.static import serve
import xadmin

from user.views import *
from organization.views import *
from iMooc.settings import MEDIA_ROOT

urlpatterns = [
]

iMooc/apps/organization/urls.py
from django.conf.urls import url

from .views import *
from operation.views import AddUserAskView

urlpatterns = [
    # 课程机构列表页
    url(r'^list/$', OrgView.as_view(), name='org_list'),
    url(r'^add_ask/$', AddUserAskView.as_view(), name='add_ask'),
    url(r'^home/(?P<org_id>\d+)/$', OrgHomeView.as_view(), name='org_home'),
    url(r'^course/(?P<org_id>\d+)/$', OrgCourseView.as_view(), name='course'),
    url(r'^desc/(?P<org_id>\d+)/$', OrgDescView.as_view(), name='org_desc'),
    url(r'^teacher/(?P<org_id>\d+)/$', OrgTeacherView.as_view(), name='teacher'),
    # 机构收藏
    url(r'^add_fav/$', AddFavView.as_view(), name='add_fav'),
    # 讲师列表页
    url(r'^teacher_list/$', TeacherListView.as_view(), name='teacher_list'),
    url(r'^teacher_detail/(?P<teacher_id>\d+)/$', TeacherDetail.as_view(), name='teacher_detail'),
]

iMooc/apps/user/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    # 个人资料
    url(r'^info/$', UserInfoView.as_view(), name='user_info'),
    # 我的课程
    url(r'^mycourse/$', MyCourseView.as_view(), name='mycourse'),
    # 我的收藏课程
    url(r'^fav_course/$', FavCourseView.as_view(), name='fav_course'),
    # 我的收藏机构
    url(r'^fav_org/$', FavOrgView.as_view(), name='fav_org'),
    # 我的收藏教师
    url(r'^fav_teacher/$', FavTeacherView.as_view(), name='fav_teacher'),
    # 我的消息
    url(r'^center_msg/$', CenterMsgView.as_view(), name='center_msg'),

    # 用户头像上传
    url(r'^image/upload/$', UploadImageView.as_view(), name='image_upload'),
    # 用户个人中心修改密码
    url(r'^update/pwd/$', UpdatePwdView.as_view(), name='update_pwd'),
    # 向新邮箱发送验证码
    url(r'^send_new_email_code/$', SendNewEmailCodeView.as_view(), name='send_new_email_code'),
    # 修改新邮箱
    url(r'^update_email/$', UpdateEmailView.as_view(), name='update_email'),
]

iMooc/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.views.static import serve
import xadmin

from user.views import *
from organization.views import *

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^login/', LoginView.as_view(), name='login'),
    url(r'^logout/', LogoutView.as_view(), name='logout'),
    url(r'^register/', RegisterView.as_view(), name='register'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^active/(?P<active_code>.*)/', ActiveUserView.as_view(), name='user_active'),
    url(r'^forget/', ForgetPwdView.as_view(), name='forget'),
    url(r'^reset/(?P<reset_code>.*)/', ResetView.as_view(), name='reset'),
    url(r'^modify_pwd/', ModifyPwdView.as_view(), name='modify_pwd'),

    # 课程机构url配置
    url(r'^org/', include('organization.urls', namespace='org')),
    # 课程url配置
    url(r'^course/', include('course.urls', namespace='course')),
    # 讲师url配置
    url(r'^teacher/', include('organization.urls', namespace='teacher')),
    # 用户url配置
    url(r'^users/', include('user.urls', namespace='user')),
    # 配置上传文件的访问处理函数
    url(r'^media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),
    # 配置静态资源的访问处理函数
    url(r'^static/(?P<path>.*)', serve, {'document_root': settings.STATIC_ROOT}),
]
# 全局404页面配置
hander404 = 'users.views.page_not_found'
# 全局500页面配置
hander500 = 'users.views.page_error'

iMooc/apps/course/models.py
from datetime import datetime

from django.db import models

from organization.models import CourseOrg, Teacher


class Course(models.Model):
    course_org = models.ForeignKey(CourseOrg, verbose_name='所属课程机构', null=True)
    name = models.CharField(max_length=50, verbose_name='课程名称')
    desc = models.CharField(max_length=300, verbose_name='课程描述')
    detail = models.TextField(verbose_name='课程详情')
    teacher = models.ForeignKey(Teacher, verbose_name='讲师', null=True, blank=True)
    degree = models.CharField(choices=(('cj', '初级'), ('zj', '中级'), ('gj', '高级')), max_length=2, verbose_name='等级')
    is_banner = models.BooleanField(default=False, verbose_name='是否轮播')
    learn_times = models.IntegerField(default=0, verbose_name='学习时长(分钟数)')
    students = models.IntegerField(default=0, verbose_name='学习人数')
    fav_nums = models.IntegerField(default=0, verbose_name='收藏人数')
    image = models.ImageField(upload_to='course/%Y/%m', verbose_name='封面图', max_length=100)
    click_nums = models.IntegerField(default=0, verbose_name='点击数')
    category = models.CharField(default='后端开发', max_length=20, verbose_name='课程类别')
    you_need_know = models.CharField(max_length=300, default='', verbose_name='课程须知')
    teacher_tell = models.CharField(max_length=300, default='', verbose_name='老师告诉你能学到什么')
    tag = models.CharField(default='', verbose_name='课程标签', max_length=10)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '课程'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    # 获取学习用户
    def get_learn_users(self):
        return self.usercourse_set.all()[:5]

    def get_learn_users_nums(self):
        return self.usercourse_set.all().count()

    # 获取全部课程
    def get_course_lesson(self):
        all_lessons = self.lesson_set.all()

        return all_lessons

    # 获取课程章节数
    def get_zj_nums(self):
        all_lessons = self.lesson_set.all()
        lessons_nums = all_lessons.count()

        return lessons_nums


class Lesson(models.Model):
    course = models.ForeignKey(Course, verbose_name='课程')
    name = models.CharField(max_length=100, verbose_name='章节名')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '章节'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    # 获取全部视频
    def get_all_video(self):
        all_video = self.video_set.all()

        return all_video


class Video(models.Model):
    lesson = models.ForeignKey(Lesson, verbose_name='章节')
    name = models.CharField(max_length=100, verbose_name='视频名称')
    url = models.CharField(max_length=200, default='', verbose_name='访问地址')
    learn_times = models.IntegerField(default=0, verbose_name='视频时长(分钟数)')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '视频'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseResource(models.Model):
    course = models.ForeignKey(Course, verbose_name='课程')
    name = models.CharField(max_length=100, verbose_name='名称')
    download = models.FileField(upload_to='course/resource/%Y/%m', verbose_name='资源文件', max_length=100)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '课程资源'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

iMooc/apps/user/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class UserProfile(AbstractUser):
    nick_name = models.CharField(max_length=50, verbose_name='昵称', default='')
    birthday = models.DateField(verbose_name='生日', default=datetime.now, null=True, blank=True)
    gender = models.CharField(choices=(('male', '男'), ('female', '女')), max_length=6, default='female')
    address = models.CharField(max_length=100, default='')
    mobile = models.CharField(max_length=11, null=True, blank=True)
    image = models.ImageField(upload_to='image/%Y/%m', default='image/default.png', max_length=100)

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username

    def unread_nums(self):
        from operation.models import UserMessage

        return UserMessage.objects.filter(user=self.id, has_read=False).count()


class EmailVerifyRecord(models.Model):
    SEND_EMAIL_TYPE = (
        ('register', '注册'),
        ('forget', '找回密码'),
        ('update_email', '修改邮箱'),
    )

    code = models.CharField(max_length=20, verbose_name='验证码')
    email = models.EmailField(max_length=50, verbose_name='邮箱')
    send_type = models.CharField(choices=SEND_EMAIL_TYPE, max_length=30, verbose_name='验证码类型')
    send_time = models.DateTimeField(default=datetime.now, verbose_name='发送时间')

    class Meta:
        verbose_name = '邮箱验证码'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '邮箱%s 验证码:%s' % (self.email, self.code)


class Banner(models.Model):
    title = models.CharField(max_length=100, verbose_name='标题')
    image = models.ImageField(upload_to='banner/%Y/m', verbose_name='轮播图', max_length=100)
    url = models.URLField(max_length=200, verbose_name='访问地址')
    index = models.IntegerField(default=100, verbose_name='顺序')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '轮播图'
        verbose_name_plural = verbose_name

iMooc/apps/operation/forms.py
__author__ = 'gengwenhao'
__date__ = '2017/10/10 22:02'
import re

from django import forms

from .models import UserAsk


class UserAskForm(forms.ModelForm):
    class Meta:
        model = UserAsk
        fields = ['name', 'mobile', 'course_name']

    def clean_mobile(self):
        # 验证手机号码是否合法
        mobile = self.cleaned_data['mobile']
        REGEX_MOBILE = '^1[358]\d{9}$|^&147\d{8}$|^&176\d{8}$'
        p = re.compile(REGEX_MOBILE)
        if p.match(mobile):
            return mobile
        else:
            raise forms.ValidationError('手机号码非法', code='mobile_invalid')

iMooc/apps/organization/forms.py
__author__ = 'gengwenhao'
__date__ = '2017/10/10 13:14'
from django import forms

iMooc/apps/course/views.py
from django.shortcuts import render, HttpResponse
from django.views.generic.base import View
from django.db.models import Q
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger

from .models import *
from operation.models import UserFavourite, CourseComments, UserCourse
from utils.mixin_utils import LoginRequiredMixin


# 课程列表
class CourseListView(View):
    def get(self, request):
        cur_nav = 'course'

        all_courses = Course.objects.all().order_by('-add_time')

        hot_courses = Course.objects.all().order_by('-click_nums')[:3]

        # 课程搜索
        search_keywords = request.GET.get('keywords', '')

        if search_keywords:
            all_courses = all_courses.filter(
                Q(name__icontains=search_keywords) | Q(desc__icontains=search_keywords) | Q(
                    detail__icontains=search_keywords))

        # 排序
        sort = request.GET.get('sort', '')
        if sort:
            if sort == 'students':
                all_courses = all_courses.order_by('-students')

            elif sort == 'hot':
                all_courses = all_courses.order_by('-click_nums')

        # 对课程进行分页
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1

        p = Paginator(all_courses, 9, request=request)

        org_nums = all_courses.count()

        all_courses = p.page(page)

        return render(request, 'course-list.html', locals())


# 课程详情
class CourseDetailView(View):
    def get(self, request, course_id):
        course_has_fav = False
        course_org_has_fav = False

        course = Course.objects.get(id=int(course_id))
        course.click_nums += 1
        course.save()

        if request.user.is_authenticated():
            if UserFavourite.objects.filter(user=request.user, fav_id=course.id, fav_type=1):
                course_has_fav = True
            if UserFavourite.objects.filter(user=request.user, fav_id=course.course_org.id, fav_type=2):
                course_org_has_fav = True

        tag = course.tag
        if tag:
            relate_courses = Course.objects.filter(tag=tag)[:1]
        else:
            relate_courses = []

        return render(request, 'course-detail.html', locals())


# 课程章节信息
class CourseInfoView(LoginRequiredMixin, View):
    def get(self, request, course_id):
        course = Course.objects.get(id=int(course_id))
        all_resource = CourseResource.objects.filter(course=course)

        # 查询用户是否已经关联了该课程
        user_courses = UserCourse.objects.filter(user=request.user, course_id=course_id)
        if not user_courses:
            user_course = UserCourse(user=request.user, course_id=course_id)
            user_course.save()

        # 获取该课程的所有学员
        user_courses = UserCourse.objects.filter(course=course)

        # 取出所有学员的id
        user_ids = [user_course.user_id for user_course in user_courses]
        all_user_courses = UserCourse.objects.filter(user_id__in=user_ids)

        # 取出所有课程id
        course_ids = [user_course.course.id for user_course in all_user_courses]

        # 获取该课程的同学还学过的课程
        relate_courses = Course.objects.filter(id__in=course_ids).order_by('-click_nums')[:5]

        return render(request, 'course-video.html', locals())


# 课程评论
class CommentView(LoginRequiredMixin, View):
    def get(self, request, course_id):
        course = Course.objects.get(id=int(course_id))
        all_comments = CourseComments.objects.filter(course=course)[:10]
        all_resource = CourseResource.objects.filter(course=course)
        # 获取该课程的所有学员
        user_courses = UserCourse.objects.filter(course=course)

        # 取出所有学员的id
        user_ids = [user_course.user_id for user_course in user_courses]
        all_user_courses = UserCourse.objects.filter(user_id__in=user_ids)

        # 取出所有课程id
        course_ids = [user_course.course.id for user_course in all_user_courses]

        # 获取该课程的同学还学过的课程
        relate_courses = Course.objects.filter(id__in=course_ids).order_by('-click_nums')[:5]

        return render(request, 'course-comment.html', locals())


class AddCommentView(View):
    def post(self, request):
        # 判断用户登陆状态
        if not request.user.is_authenticated():

            return HttpResponse('{"status":"fail", "msg":"用户未登陆"}', content_type='application/json')
        else:
            user = request.user
            course_id = int(request.POST.get('course_id', 0))
            comments = request.POST.get('comments', '')
            if course_id > 0 and comments:
                try:
                    CourseComments.objects.create(user=user, course_id=course_id, comments=comments)
                except:
                    return HttpResponse('{"status":"fail", "msg":"出错"}', content_type='application/json')

                return HttpResponse('{"status":"success", "msg":"评论成功"}', content_type='application/json')


class VideoPlayView(View):
    def get(self, request, video_id):
        video = Video.objects.get(id=int(video_id))
        course = video.lesson.course
        all_comments = CourseComments.objects.filter(course=course)[:10]
        all_resource = CourseResource.objects.filter(course=course)
        # 获取该课程的所有学员
        user_courses = UserCourse.objects.filter(course=course)

        # 取出所有学员的id
        user_ids = [user_course.user_id for user_course in user_courses]
        all_user_courses = UserCourse.objects.filter(user_id__in=user_ids)

        # 取出所有课程id
        course_ids = [user_course.course.id for user_course in all_user_courses]

        # 获取该课程的同学还学过的课程
        relate_courses = Course.objects.filter(id__in=course_ids).order_by('-click_nums')[:5]

        return render(request, 'course-play.html', locals())

iMooc/apps/operation/views.py
from django.shortcuts import render, HttpResponse
from django.views.generic.base import View

from .forms import UserAskForm


# Create your views here.
class AddUserAskView(View):
    # 用户添加咨询
    def post(self, request):
        userask_form = UserAskForm(request.POST)
        if userask_form.is_valid():
            user_ask = userask_form.save(commit=True)
            return HttpResponse("{'status':'success'}", content_type='application/json')
        else:
            return HttpResponse("{'status':'fail', 'msg':'添加出错'}", content_type='application/json')

iMooc/templates/org_base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>{% block title %}机构首页{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    {% block custom_css %}{% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
    {% block custom_js %}{% endblock %}
</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
        <div class="header2 header">
            <div class="top">
                <div class="wp">
                    <div class="fl"><p>微信：<b>HnGenWH</b></p></div>
                    <!--登录后跳转-->


                    {% if request.user.is_authenticated %}
                        <div class="personal">
                            <dl class="user fr">
{#                                <dd>{{ request.user.username }}<img class="down fr" src="{% static '/images/top_down.png' %}"/></dd>#}
                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                            </dl>
                            <div class="userdetail">
                                <dl>
                                    <dt><img width="80" height="80"
                                             src="{{ MEDIA_URL }}{{ request.user.image }}"/>
                                    </dt>
                                    <dd>
                                        <h2>{{ request.user.nick_name|default_if_none:'' }}</h2>
                                        <p>{{ request.user.username|default_if_none:'' }}</p>
                                    </dd>
                                </dl>
                                <div class="btn">
                                    <a class="personcenter fl" href="{% url 'user:user_info' %}">进入个人中心</a>
                                    <a class="fr" href="{% url 'logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'user:center_msg' %}">
                        <div class="msg-num"><span id="MsgNum">0</span></div>
                        </a>
                    {% else %}
                        <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">登录</a>
                    {% endif %}


                </div>
            </div>
            <div class="middle companyheader">
                <div class="wp">
                    <img class="fl" style="width: 112px;height: 103px" src="{{ MEDIA_URL }}{{ course_org.image }}"/>
                    <div class="head fl">
                        <h1>
                            {{ course_org.name }}
                            <img src="{% static 'images/authentication.png' %}"/>
                            <img src="{% static 'images/gold.png' %}"/>
                        </h1>
                        <p class="fl">
                            <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                            <span class="precision company-credit" data-star-scope="5.0"></span>
                            <span class="key">5.0</span>
                        </p>
                    </div>
                    <div class="btn fr collectionbtn  notlogin
                 " data-favid="22" data-fav-type="1">
                        {% if has_fav %}已收藏{% else %}收藏{% endif %}
                    </div>

                </div>
            </div>
        </div>
    </header>
</section>
<section>
    <div class="wp">
        <ul class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
            <li><a href="{% url 'org:org_list' %}">课程机构</a>></li>
            <li>{% block page_path %}机构首页{% endblock %}</li>
        </ul>
    </div>
</section>
<section>
    <div class="wp list personal_list comp">
        <div class="left">
            <ul>
                <li class="{% ifequal current_page 'home' %}active2{% endifequal %}"><a
                        href="{% url 'org:org_home' course_org.id %}">机构首页</a></li>
                <li class="{% ifequal current_page 'course' %}active2{% endifequal %}"><a
                        href="{% url 'org:course' course_org.id %}">机构课程</a></li>
                <li class="{% ifequal current_page 'desc' %}active2{% endifequal %}"><a
                        href="{% url 'org:org_desc' course_org.id %}">机构介绍</a></li>
                <li class="{% ifequal current_page 'teacher' %}active2{% endifequal %}"><a
                        href="{% url 'org:teacher' course_org.id %}">机构讲师</a></li>
            </ul>
        </div>


        {% block right_form %}

        {% endblock %}
    </div>
</section>
<!--sidebar start-->
<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<!--sidebar end-->
<!--header start-->
</div>
<!--弹出省省市-->
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static '/js/validateDialog.js' %}" type="text/javascript"></script>
<script src="{% static '/js/deco-common.js' %}" type="text/javascript"></script>
<script type="text/javascript" src="{% static 'js/plugins/jquery.raty.js' %}"></script>
<script type="text/javascript">
    //收藏分享
    //收藏分享
    function add_fav(current_elem, fav_id, fav_type) {
        $.ajax({
            cache: false,
            type: "POST",
            url: "/org/add_fav/",
            data: {'fav_id': fav_id, 'fav_type': fav_type},
            async: true,
            beforeSend: function (xhr, settings) {
                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            },
            success: function (data) {
                if (data.status == 'fail') {
                    if (data.msg == '用户未登录') {
                        window.location.href = "/login/";
                    } else {
                        alert(data.msg)
                    }

                } else if (data.status == '/success/') {
                    current_elem.text(data.msg)
                }
            },
        });
    }

    $('.collectionbtn').on('click', function () {
        add_fav($(this), {{ course_org.id }}, 2);
    });

    $(function () {
        var $precision = $('.precision'),
            score = $precision.attr('data-star-scope'),
            option = {
                half: true,
                path: '{% static 'images/' %}',
                precision: true,
                size: 24,
                starOff: 'g_star.png',
                starOn: 'r_star.png',
                starHalf: 'h_star.png',
                hints: ['极差', '差', '一般', '好评', '非常满意'],
                noRatedMsg: '暂时还未获得评价！',
                readOnly: true,
                score: score
            };
        $precision.raty(option);

        $('.jsFavBtn').on('click', function () {
            var type = $(this).attr('data-fav-type');
            if (type == '1') {
                favPraise($(this), 'fav', 1, '收藏');

            } else if (type == '3') {
                favPraise($(this), 'fav', 3);

            } else if (type == '11') {
                favPraise($(this), 'pra', 1);

            } else if (type == '4') {
                favPraise($(this), 'fav', 4);

            }
        });
    })
</script>


<script type="text/javascript">
    $(function () {
        $('.recordbtn1').click(function () {
            $('.recordbox1').show();
        });
        $('.recordbtn2').click(function () {
            $('.recordbox2').show();
        });

        $('.imgslide').unslider({
            speed: 500,               //  The speed to animate each slide (in milliseconds)
            delay: 3000,              //  The delay between slide animations (in milliseconds)
            complete: function () {
            },  //  A function that gets called after every slide animation
            keys: true,               //  Enable keyboard (left, right) arrow shortcuts
            dots: true,               //  Display dot navigation
            fluid: false              //  Support responsive design. May break non-responsive designs
        });
        var unslider = $('.imgslide').unslider();
        $('.unslider-arrow').click(function () {
            var fn = this.className.split(' ')[1];
            unslider.data('unslider')[fn]();
        });
    });
</script>

</body>
</html>

iMooc/templates/usercenter-fav-course.html
{% extends 'usercenter-base.html' %}

{% block title %}我的收藏- iMooc在线网{% endblock %}

{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'user:user_info' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_content %}
    <div class="right">
        <div class="personal_des Releasecont">
            <div class="head">
                <h1>我的收藏</h1>
            </div>
        </div>
        <div class="personal_des permessage">
            <div class="head">
                <ul class="tab_header messagehead">
                    <li><a href="{% url 'user:fav_org' %}">课程机构</a></li>
                    <li><a href="{% url 'user:fav_teacher' %}">授课教师 </a></li>
                    <li class="active"><a href="{% url 'user:fav_course' %}">公开课程</a></li>
                </ul>
            </div>
            <div class="companycenter">
                <div class="group_list brief">
                    {% for fav_course in all_fav_courses %}
                        <div class="module1_5 box">
                            <a href="{% url 'course:course_detail' fav_course.id %}">
                                <img width="214" height="190"
                                     src="{{ MEDIA_URL }}{{ fav_course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'course:course_detail' fav_course.id %}"><h2>{{ fav_course.name }}</h2>
                                </a>
                                <span class="fl">时长：<i class="key">{{ fav_course.learn_times }}</i></span>
                                <span class="fr">学习人数：{{ fav_course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ fav_course.course_org.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ fav_course.id }}"></span>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}